- src/commons/filter/http-exception.filter.ts
- src/main.ts
> feat: add filter & pipe

- src/apis/posts/dto/create-post.dto.ts
- src/apis/posts/interfaces/post-service.interfaces.ts
- src/apis/posts/posts.controller.ts
- src/apis/posts/posts.module.ts
- src/apis/posts/posts.service.ts
- src/app.module.ts
> feat: post-CRUD

- src/apis/auth/auth.controller.ts
- src/apis/auth/auth.service.ts
- src/apis/users/dto/res.dto.ts
- src/apis/users/users.controller.ts
> feat: local-login-for-test 

- src/apis/comments/comments.controller.ts
- src/apis/comments/comments.module.ts
- src/apis/comments/comments.service.ts
- src/apis/comments/dto/create-post-comment.dto.ts
- src/apis/comments/interfaces/post-comment-service.interface.ts
- src/apis/posts/posts.controller.ts
- src/app.module.ts
> feat: comment CRUD

- src/apis/studies/dto/update-study.dto.ts
- src/apis/studies/interfaces/studies-service.interface.ts
- src/apis/studies/studies.controller.ts
- src/apis/studies/studies.service.ts
> feat: add study update

- src/apis/studies/dto/create-study.dto.ts
- src/apis/studies/dto/update-study.dto.ts
- src/apis/studies/entities/study.entity.ts
- src/apis/studies/studies.controller.ts
> feat: add study content

- src/apis/chatgpts/chatgpts.service.ts
- src/apis/chatgpts/interfaces/chatgpts-service.interface.ts
> feat : chatgpt-interface

- src/apis/studies/interfaces/studies-service.interface.ts
- src/apis/studies/studies.controller.ts
- src/apis/studies/studies.service.ts
> feat: add study detail

- src/apis/studies/studies.service.ts
> fix: add join count

- src/apis/users/dto/res.dto.ts
- src/apis/users/interfaces/users-serviice.interface.ts
- src/apis/users/users.controller.ts
- src/apis/users/users.service.ts
> feat: find-user

- src/apis/chatgpts/chatgpts.controller.ts
- src/apis/chatgpts/chatgpts.service.ts
- src/apis/questions/dto/continue-question.dto.ts
- src/apis/questions/interfaces/questions-service.interface.ts
- src/apis/questions/questions.controller.ts
- src/apis/questions/questions.service.ts
> feat : question search, filter

- src/apis/auth/strategies/jwt-access.strategy.ts
- src/apis/questions/questions.service.ts
- src/apis/users/users.service.ts
프론트로부터 token 추출위치 cookie->header로 변경
> fix/user-token 

- src/apis/auth/auth.controller.ts
> feat: logout

- src/apis/questions/questions.controller.ts
- src/apis/questions/questions.service.ts
> fix : question-search

- src/apis/messages/dto/create-message.dto.ts
- src/apis/messages/entities/message.entity.ts
- src/apis/messages/interfaces/messages-service.interface.ts
- src/apis/messages/messages.controller.ts
- src/apis/messages/messages.module.ts
- src/apis/messages/messages.service.ts
- src/apis/users/entities/user.entity.ts
- src/app.module.ts
message service 추가
수신자 & 발신자 구분, 생성, 삭제, 조회 기능
> feat: add message service

- src/apis/auth/auth.controller.ts
> fix: user-logout

- src/commons/dto/page-req.dto.ts
> fix: page size

- src/apis/comments/comments.controller.ts
- src/apis/comments/comments.service.ts
- src/apis/comments/interfaces/post-comment-service.interface.ts
> fix: comment get

- src/apis/studies/interfaces/studies-service.interface.ts
- src/apis/studies/studies.controller.ts
- src/apis/studies/studies.service.ts
- src/commons/dto/page-req.dto.ts
study 페이지 네이션 topic추가 및 topic 조회 주석처리
> fix: study page

- src/apis/studies/interfaces/studies-service.interface.ts
- src/apis/studies/studies.controller.ts
- src/apis/studies/studies.service.ts
- src/commons/dto/page-req.dto.ts
> fix: change page dto

- src/apis/chatgpts/chatgpts.service.ts
- src/apis/questions/dto/continue-question.dto.ts
> fix: chatgpt engineered prompt added

- src/apis/chatgpts/chatgpts.service.ts
> fix: chatgpt maxtoken modified

- src/apis/posts/posts.service.ts
> fix: post page

- src/app.module.ts
> fix: timezone

- src/apis/messages/interfaces/messages-service.interface.ts
- src/apis/messages/messages.controller.ts
- src/apis/messages/messages.service.ts
> feat: message pagination

- src/apis/chatgpts/chatgpts.service.ts
- src/apis/questionDetails/question-details.service.ts
- src/apis/questions/questions.controller.ts
- src/apis/questions/questions.service.ts
question 조회 시 정렬방식 변경(questionDetails createdAt ASC), GPT 모델 변경(16k)
> fix:question, chatgpt

- src/apis/questionDetails/entities/questionDetail.entity.ts
- src/apis/questions/questions.controller.ts
- src/apis/questions/questions.service.ts
- src/apis/studies/studies.controller.ts
ManyToOne question.questionDetails ondelete:CASCADE옵션 추가
> fix:question-entity 

- src/apis/chatgpts/chatgpts.service.ts
- src/apis/questions/questions.service.ts
질문 생성 시 기존 빈 질문 존재하면 생성 안되게 수정
> fix:create-question

- src/apis/questionDetails/dto/create-question-detail.dto.ts
- src/apis/questionDetails/entities/questionDetail.entity.ts
- src/apis/questionDetails/interfaces/question-details-service.interface.ts
- src/apis/questionDetails/question-details.service.ts
- src/apis/questions/dto/continue-question.dto.ts
- src/apis/questions/entities/question.entity.ts
- src/apis/questions/interfaces/questions-service.interface.ts
- src/apis/questions/questions.controller.ts
- src/apis/questions/questions.service.ts
- src/apis/studies/dto/create-study.dto.ts
- src/apis/studies/dto/update-study.dto.ts
- src/apis/studies/entities/study.entity.ts
- src/commons/dto/page-req.dto.ts
- src/commons/enum/enum.ts
가장 마지막 질문이 제목이 되도록 변경
question-detail에 topic, type, library 컬럼 생성
> fix:question,question-detail

- src/apis/questions/questions.service.ts
> fix:findRecentQuestion

- src/apis/questions/interfaces/questions-service.interface.ts
- src/apis/questions/questions.controller.ts
- src/apis/questions/questions.service.ts
내질문 조회 where user.id = userId 추가
> fix:find-my-question

- src/apis/questionDetails/interfaces/question-details-service.interface.ts
- src/apis/questionDetails/question-details.controller.ts
- src/apis/questionDetails/question-details.service.ts
> feat: add question details find many

- src/apis/questionDetails/question-details.controller.ts
question-details => api/question-details
> fix: controller api

- src/apis/studies/entities/applicant.entity.ts
- src/apis/studies/entities/study.entity.ts
- src/apis/studies/studies.module.ts
- src/apis/studies/studies.service.ts
- src/apis/users/entities/user.entity.ts
applicant entity 생성 & study 목록조회 method => query builder
> feat: applicant entity

- src/apis/chatgpts/chatgpts.service.ts
- src/commons/enum/enum.ts
> fix:chatgpt-prompt

- src/apis/studies/interfaces/studies-service.interface.ts
- src/apis/studies/studies.controller.ts
- src/apis/studies/studies.service.ts
join study 스터디장 허락방식 => 자유참여로 변경
> fix: join study

- src/apis/studies/studies.controller.ts
- src/apis/studies/studies.service.ts
console.log 삭제, 안쓰는 endpoint 삭제
> chore: console delete

- src/apis/questionDetails/question-details.service.ts
> chore: import delete
